apiVersion: networking.k8s.io/v1 # API version for Ingress resource
kind: Ingress
metadata:
  name: taskmaster-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: taskmaster.local # Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskmaster-ssvc
                port:
                  number: 80
  tls: # Enable TLS for HTTPS (Optional)
    - hosts:
        - taskmaster.local
      secretName: taskmaster-tls-secret # Provide a TLS secret for HTTPS (optional)
